apiVersion: apps/v1
kind: Deployment
metadata:
  name: book
  namespace: console-app ## Project Name
spec:
  selector:
    matchLabels:
      app: book
  replicas: 1
  template:
    metadata:
      labels:
        app: book
    spec:
      containers:
        - name: book
          image: 'quay.io/redhattraining/books:v0.9' ## Image path but it will give errors which we will troubleshoot further then modify to quay.io/redhattraining/books:v1.4
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
          env:
            - name: DB_HOST
              value: database.console-apps.svc.cluster.local ## Database hostname or we can take cluster IP of Database Pod
            - name: DB_PORT
              value: '5432'
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: postgres
            - name: DB_NAME
              value: postgres
