apiVersion: apps/v1
kind: Deployment
metadata:
  name: book
  namespace: console-app
spec:
  selector:
    matchLabels:
      app: book
  replicas: 1
  template:
    metadata:
      labels:
        app: book
    spec:
      containers:
        - name: book
          image: 'quay.io/redhattraining/books:v0.9'
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
          env:
            - name: DB_HOST
              value: database.console-apps.svc.cluster.local
            - name: DB_PORT
              value: '5432'
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: postgres
            - name: DB_NAME
              value: postgres
